title: Bench News
description: Blog for Bench News and Updates
theme: minima

# IMPORTANT for project pages
url: "https://bench-india.github.io"
baseurl: "/Bench-news"     # <= repo name starting with a slash

show_excerpts: true
# Optional: GitHub Pages-whitelisted plugins
plugins:
  - jekyll-feed           # RSS feed
  - jekyll-seo-tag        # SEO tags
