title: Bench News
description: Updates from Bench
theme: minima             # built-in theme, no extra setup
show_excerpts: true

# Because this is a *project* site (not username.github.io), add:
url: "https://Bench-India.github.io"
baseurl: "/Bench-news"    # repo name prefixed with a slash

# Optional: GitHub Pages-whitelisted plugins
plugins:
  - jekyll-feed           # RSS feed
  - jekyll-seo-tag        # SEO tags
